### ISSUE TITLE
transfer to posthtml ?

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-hash#1]
Perhaps there is a desire to move to `posthtml` org ?

**Comment by Scrum** [comment]
there is an analogue to your package, maybe you will be interested
[posthtml-cache](https://github.com/posthtml/posthtml-cache)

the name of your package is more correct

**Comment by metonym** [comment]
Hello @Scrum, I am definitely interested in moving the repo!

`posthtml-cache` shares functional similarities. However, I believe it is practical to generate an id from hashing the file buffer.

Therefore, re-building static assets supports:
- _long-term caching_: hash doesn't change if content doesn't change
- _cache busting_: hash changes when the content changes

I am open to your thoughts on this as well.

**Comment by metonym** [comment]
I've initiated a transfer.

**Comment by Scrum** [comment]
> I've initiated a transfer.

done

Your approach undoubtedly has more advantages before versioning through the get parameter.
- proxies
- date of modification when packaging

under these criteria it is sometimes very difficult to achieve rehashing
