### ISSUE TITLE
Css OR JS only, not both?

### ISSUE THREAD

**Issue by frederikhors** [posthtml/posthtml-hash#38]
Is there a way to only hash css OR js files? Not both?

Thanks for your work.

**Comment by frederikhors** [comment]
I already have js hashed. Only need to operate on css.

**Comment by metonym** [comment]
Currently, it looks for both CSS/JS. However, I think it should support the ability to include only certain extensions (like in your case for CSS).

**Comment by metonym** [comment]
@frederikhors 

Released in [v0.3.0](https://www.npmjs.com/package/posthtml-hash).

There are two new options added to enable/disable hashing for CSS or JS. By default, both `css` and `js` flags are set to `true`.

```js
const { hash } = require("posthtml-hash");

hash({
  css: true,
  js: true
})
```

**Hash CSS files only**

```js
hash({
 js: false
})
```

**Hash JS files only**

```js
hash({
  css: false
})
```

Thank you for raising this issue.

**Comment by frederikhors** [comment]
@metonym this is great! However I was thinking about when you have free from Rollup an hash in js files (using `[hash]` in the name) but not in `index.html`.

Now I have disabled the `[hash]` in the file name but it would be awesome to add also this feature.

**Comment by metonym** [comment]
@frederikhors I like your idea because it would be a more declarative, tacit way to hash a file. In addition, you could incorporate the hash length in the patten (i.e. `script[hash:12].js`).
