### ISSUE TITLE
Doesn't work with Rollup output.entryFileNames

### ISSUE THREAD

**Issue by frederikhors** [posthtml/posthtml-hash#45]
_I'm opening this and I'm closing https://github.com/posthtml/posthtml-hash/issues/44 because too chatty._

This plugin doesn't work with [`Rollup` `output.entryFileNames`](https://rollupjs.org/guide/en/#outputentryfilenames) (read https://github.com/posthtml/posthtml-hash/issues/44).

**Comment by frederikhors** [comment]
I am so sad about this update that it appears to me in every CI process.

And I'm also very sad because you don't understand the need (not a whim) of every user who uses this amazing library with Rollup.

**Comment by metonym** [comment]
I added a "help wanted" label.

**Comment by metonym** [comment]
Have you tried @rollup/plugin-html as suggested by https://github.com/sveltejs/template/issues/39#issuecomment-648056217?

**Comment by frederikhors** [comment]
Not yet. I'll try it. But I really like your one, unfortunately.

**Comment by frederikhors** [comment]
@metonym, I finally found some free time to fix this problem.

And I solved it. Almost.

I'm using Rollup with this (common for SPA projects) code:

```js
export default {
  input: './main.js',
  output: {
    format: 'esm',
    dir: 'build',
    entryFileNames: 'bundle.js',
    chunkFileNames: `bundle.chunk${production ? '.[hash]' : ''}.js`
  },
}
```

## THE PROBLEM

Since I cannot use this:

```js
entryFileNames: 'bundle.[hash].js'
```

because [`[hash]` is an "already taken" keyword by Rollup](https://rollupjs.org/guide/en/#outputentryfilenames) (see this too for more: https://github.com/posthtml/posthtml-hash/issues/44)

I need to use this code (in two different location of my `rollup.config.js` for both development and production flow):

```js
fs.renameSync('dist/bundle.js', 'dist/bundle.[hash].js')
```

## SO THE REQUEST

1. Can we change the `[hash]` keyword?

    With something like `(hash-)` or `__hash__` or `[oh-my-hash]` or `[posthtml-hash]`?

1. Since I know you care not to do breaking changes, can we at least add an option to use a custom placeholder?

    E.g. like:

    ```js
    hash({
      path: "public", // default: "",
      placeholder: "[oh-my-hash]" // default: "[hash]"
    });
    ```

Thank you.

**Comment by metonym** [comment]
@frederikhors That's a perfectly reasonable request. Thank you for investing time in proposing a solution.

It's definitely worth re-considering the "hash" keyword.

Just a thought, but Webpack actually differentiates between "hash," "chunkhash" and "contenthash":

| Template | Description                                       |
| :------------ | :------------------------------------------ |
| hash          | The hash of the module identifier |
| contenthash | the hash of the content of a file, which is different for each asset |
| chunkhash | The hash of the chunk content |

[Source](https://webpack.js.org/configuration/output/#template-strings)

It seems that for most cases, "contenthash" or "chunkhash" is actually more appropriate.

---

If we can decide on new hash name pattern, I'm not opposed to increasing the major version.

However, I like your second option of being able to override the default pattern. Then, in the future, we can always change the actual default value.

**Comment by frederikhors** [comment]
I found a new problem with brackets and purgecss: https://github.com/FullHuman/purgecss/issues/453.

**Comment by metonym** [comment]
@frederikhors Allowing a custom regular expression should address that issue (#47 )

**Comment by metonym** [comment]
@frederikhors Released in 1.1.

Please let me know if there are any issues.

**Comment by frederikhors** [comment]
Tried. It works amazing!

Glad that there are people like you in the world.

**Comment by metonym** [comment]
Great to hear – thanks to you for following up on this to improve the API
