### ISSUE TITLE
Hash length placeholder is a problem with postcss

### ISSUE THREAD

**Issue by frederikhors** [posthtml/posthtml-hash#46]
_This is something related to https://github.com/posthtml/posthtml-hash/issues/45#issuecomment-658427436._

Using `[hash]` with `postcss` plugin in Rollup is impossible because it can't create file.

## Example

I have this code:

```js
postcss({
  extract: 'bundle.[hash].css' // this creates my css file
}),
```

which works.

If I use this instead:

```js
postcss({
  extract: 'bundle.[hash:8].css' // this doesn't work
}),
```

it creates a file named `bundle.[hash` which is obviously wrong.

So the question:

can we change the placeholder for hash length?

Can we use something like `[posthtml-hash-8]` (`[posthtml-hash-<LENGTH>]`)?

Thanks for your commitment.

**Comment by metonym** [comment]
Another solution could be to allow an optional `hashLength` parameter to be defined by the consumer.

```
hash({ path: 'public', pattern: '[oh-my-hash]', hashLength: 8 })
```
